version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: planner_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: planner_db
      MYSQL_USER: planner_user
      MYSQL_PASSWORD: planner_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - planner_network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: planner_backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql://planner_user:planner_password@mysql:3306/planner_db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - planner_network

volumes:
  mysql_data:

networks:
  planner_network:
    driver: bridge 