ALTER TABLE opdrachtgevers
ADD COLUMN IF NOT EXISTS kvk_nummer VARCHAR(20) NULL,
ADD COLUMN IF NOT EXISTS postcode VARCHAR(10) NULL,
ADD COLUMN IF NOT EXISTS stad VARCHAR(100) NULL,
ADD COLUMN IF NOT EXISTS telefoon VARCHAR(20) NULL; 