version: '2'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql://planner_user:planner_password@db:3306/planner_db
      - SECRET_KEY=kY2hkWFErBgPf3t5
      - DEBUG=False
      - ALLOWED_HOSTS=69.28.88.75,localhost
      - CORS_ORIGINS=http://69.28.88.75:80,http://localhost:80
    depends_on:
      - db
    networks:
      - planner_network
    restart: always

  db:
    image: mysql:5.7
    container_name: planner_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: planner_db
      MYSQL_USER: planner_user
      MYSQL_PASSWORD: planner_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - planner_network
    restart: always

volumes:
  mysql_data:

networks:
  planner_network:
    driver: bridge 