# employee_profiles_data.py

employee_profiles = {
    "ali": {
        "employee_id": "ali",
        "personeelsnummer": 1,
        "naam": "alikhan",
        "voornaam": "Ali",
        "tussenvoegsel": "",
        "achternaam": "Khan",
        "initialen": "A.K.",
        "email": "ali@example.com",
        "telefoon": "0612345678",
        "adres": "Straatweg",
        "huisnummer": "123",
        "huisnummer_toevoeging": "A",
        "postcode": "1234 AB",
        "stad": "Amsterdam",
        "geboortedatum": "1990-01-01",
        "geboorteplaats": "Amsterdam",
        "geslacht": "male",
        "burgerlijke_staat": "single",
        "bsn": "123456789",
        "nationaliteit": "Dutch",
        "in_dienst": "2020-01-01",
        "uit_dienst": None,
        "pas_type": "Type A",
        "pas_nummer": "123456",
        "pas_vervaldatum": "2025-01-01",
        "pas_foto": "path/to/photo.jpg",
        "pas_foto_voorzijde": "path/to/front.jpg",
        "pas_foto_achterzijde": "path/to/back.jpg",
        "contract_type": "Full-time",
        "contract_uren": 40,
        "contract_vervaldatum": "2025-01-01",
        "uurloner": True,
        "telefoonvergoeding_per_uur": 2.0,
        "maaltijdvergoeding_per_uur": 1.5,
        "de_minimis_bonus_per_uur": 0.5,
        "wkr_toeslag_per_uur": 1.0,
        "kilometervergoeding": 0.23,
        "max_km": 60,
        "hourly_allowance": 5.0
    }
    # Voeg indien nodig meer medewerkers toe...
}
